# Generated by Django 6.0.1 on 2026-01-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', '未回答')], max_length=20)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
