# Generated by Django 6.0.1 on 2026-02-02 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plus_calorie', models.FloatField(default=0.0, help_text='Calories gained')),
                ('minus_calorie', models.FloatField(default=0.0, help_text='Calories burned')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'db_table': 'records',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'created_at')},
            },
        ),
    ]
