# Generated by Django 6.0.1 on 2026-02-02 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=10)),
                ('content', models.TextField()),
                ('calorie', models.FloatField(default=0.0)),
                ('is_achieved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDailyAchieved',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_achievements', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Daily Achievement',
                'verbose_name_plural': 'Task Daily Achievements',
                'db_table': 'task_daily_achieved',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'task', 'created_at')},
            },
        ),
    ]
